version: '3'

services:
  main:
    build: .
    container_name: le-simple
    image: gbifnorway/le-simple:latest
    platform: linux/amd64
    env_file: .env
    restart: on-failure
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/srv
